---
title: digitalWrite()
categories: [ "Functions" ]
subCategories: [ "Digital I/O" ]
---


//
:ext-relative: .html

= digitalWrite()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
`HIGH` 또는 `LOW` 값을 디지털 핀에 출력합니다.

핀이 `pinMode()` 를 통해 `OUTPUT` 으로 설정되면, 그 핀의 전압은 `HIGH` 일 때 5V(또는 3.3V 보드에서 3.3V), `LOW` 일 때 0V (ground)로 설정됩니다.
[%hardbreaks]

핀이 `INPUT` 으로 설정되면, `digitalWrite()` 는 입력 핀의 내부 풀업 저항을 활성화 (`HIGH`) 또는 비활성화 (`LOW`)할 것입니다. 내장 풀업 저항을 활성화하기 위해서는 `pinMode()` 를 `INPUT_PULLUP` 으로 설정하는 것을 권장합니다. 디지털 핀 튜토리얼을 보면 더 많은 정보가 있습니다.
[%hardbreaks]

`pinMode()` 를 `OUTPUT` 으로 설정하지 않고 LED를 핀에 연결하면, `digitalWrite(HIGH)` 가 불릴 때 LED 불빛이 흐리게 나타날 수 있습니다.
명시적으로 `pinMode()` 를 설정하지 않으면 `digitalWrite()` 는 내부 풀업 저항을 활성화시킬 것이고, 그것은 마치 전류를 제한하는 큰 저항처럼 동작할 것입니다.

[%hardbreaks]

[float]
=== 문법
`digitalWrite(pin, value)`


[float]
=== 매개변수
`pin`: 핀 번호

`value`: `HIGH` 또는 `LOW`

[float]
=== 반환
없음

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 예제 코드
// Describe what the example code is all about and add relevant code
이 코드는 디지털 핀 13을 `OUTPUT` 로 만들고 1초마다 `HIGH` 와 `LOW` 사이를 전환합니다.

[source,arduino]
----
void setup() {
  pinMode(13, OUTPUT);    // 디지털 핀 13 을 출력으로 설정
}

void loop() {
  digitalWrite(13, HIGH); // 디지털 핀 13 켜기
  delay(1000);            // 1초 기다리기
  digitalWrite(13, LOW);  // 디지털 핀 13 끄기
  delay(1000);            // 1초 기다리기
}
----
[%hardbreaks]

[float]
=== 주의와 경고
A0, A1 등을 통해 아날로그 입력 핀을 디지털 핀으로 사용할 수 있습니다.


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 더보기

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/DigitalPins[Tutorial: Digital Pins^]

--
// SEE ALSO SECTION ENDS
