---
title: float
categories: [ "Variables" ]
subCategories: [ "자료형" ]
---





= float


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
부동소수점 숫자, 소수점을 가진 수를 위한 자료형.
부동소수점 수는 아나로그와 연속 값을 근사하는데 자주 쓰이는데 왜냐면 정수보다 큰 해상도를 갖기 때문이다.
부동소수점 수는 3.4028235E+38 까지 클 수 있고 -3.4028235E+38 까지 작을 수 있다. 32비트(4바이트) 정보를 저장한다.

float 는 6-7자리까지만 정밀하다. 그건 숫자의 전체 자리수를 뜻한다. 소수점 오른쪽의 자리수가 아님.
double(e.g. 15자리)을 써서 좀더 정밀도를 얻을 수 있는 다른 플랫폼과 달리, 아두이노에서 double 은 float 와 같은 크기다.

부동소수점 숫자는 정확하지 않고, 비교할 때 이상한 결과가 나올 수 있다. 예를 들어 6.0 / 3.0 이 2.0과 같지 않을 수 있다.
대신 숫자들의 차이의 절대값이 어떤 작은 수보다 작은지 체크해야한다.

부동소수점 수학은 계산할 때 정수보다 매우 느리므로, 심각한 타이밍 기능을 위해 루프가 최고로 실행되야 하는 경우에는 피해야 한다.
프로그래머는 속도를 올리기 위해 때때로 부동소수점을 정수 수학으로 변환하는 길을 간다.

float 로 수학을 하면, 소수점을 더해야 하며, 그러지 않으면 int 로 취급된다.
더 자세한 것은 link:../../constants/floatingpointconstants[부동 소수점 상수] 페이지를 보세요.

[%hardbreaks]

[float]
=== 문법
`float var = val;`

`var` - float 변수 이름
`val` - 변수에 할당할 값
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 예제 코드
// Describe what the example code is all about and add relevant code


[source,arduino]
----
float myfloat;
float sensorCalbrate = 1.117;

int x;
int y;
float z;

x = 1;
y = x / 2;          // y 는 0이 되고, int 는 분수를 저장할 수 없다.
z = (float)x / 2.0; // z 는 이제 .5 가 됨 (2.0을 써야 하며 2는 안 됨)
----


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== 더보기

[role="language"]

--
// SEE ALSO SECTION ENDS
