---
title: int
categories: [ "Variables" ]
subCategories: [ "Data Types" ]
---





= int


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
정수는 숫자 저장을 위한 기본 자료형이다.

안드로이드 우노(그리고 다른 ATmega 기반 보드)에서 int 는 16비트(2바이트) 값을 저장한다.
이 값은 -32,768 에서 32,767 (최소값 -2^15 과 최대값 (2^15) - 1).
아두이노 Due와 SAND 기반 보드(MKR1000과 Zero 같은)에서, int 는 32비트 (4바티트) 값을 저장한다.
이것은 -2,147,483,648 에서 2,147,483,647 까지(최소값 -2^31 과 최대값 (2^31) - 1).

int 의 음수는 (http://en.wikipedia.org/wiki/2%27s_complement[2's complement math])라는 기술로 저장한다.
가장높은 비트, 때때로 "sign" bit 로 참조되는, 는 숫자를 음수라고 표시한다. 비트의 나머지는 거꾸로 되고 1이 더해진다.

아두이노는 음수를 주의깊게 음수를 다루므로, 산술연산은 예상대로 투명하게 동작한다.
그러나, link:../../../structure/bitwise-operators/bitshiftright/[bitshift right operator] (>>) 를 다룰 때 예상치 못한 복잡함이 생길 수 있다.
[%hardbreaks]


[float]
=== 문법
`int var = val;`

`var` - int 변수 이름 +
`val` - 그 변수에 할당한 값

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 예제 코드
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
  int ledPin = 13;
----
[%hardbreaks]

[float]
=== 주의와 경고
When signed variables are made to exceed their maximum or minimum capacity they _overflow_.  The result of an overflow is unpredictable so this should be avoided.  A typical symptom of an overflow is the variable "rolling over" from its maximum capacity to its minimum or vice versa, but this is not always the case.  If you want this behavior, use link:../unsignedint/[unsigned int].


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== 더 볼 것

[role="language"]
* #LANGUAGE# link:../../constants/integerconstants[Integer Constants]

--
// SEE ALSO SECTION ENDS
