---
title: string
categories: [ "Variables" ]
subCategories: [ "자료형" ]
---





= string


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
텍스트 스트링은 두 가지로 나타낼 수 있다.
String 자료형을 쓸 수 있는데, 그것은 버전 0019 핵심 부분이며, 또는 스트링을 문자와 널로 끝나는 형의 배열로 만들 수 있다. 이 페이지는 후자의 방법을 설명한다.
스트링 개체는, 좀더 많은 메모리의 기능성을 주는데, 자세한 것은 link:../stringobject[String object] 페이지ᅟ를 보세요.
[%hardbreaks]

[float]
=== 문법
아래 모든 것은 스트링 선언으로 타당하다.

`char Str1[15];` +
`char Str2[8] = {'a', 'r', 'd', 'u', 'i', 'n', 'o'};` +
`char Str3[8] = {'a', 'r', 'd', 'u', 'i', 'n', 'o', '\0'};` +
`char Str4[ ] = "arduino";` +
`char Str5[8] = "arduino";` +
`char Str6[15] = "arduino";`

*문자열 선언의 가능성*

* Str1 처럼 초기화 하지 않고 문자의 배열로 선언
* Str2 처럼 문자(한 문자 더)의 배열을 선언하고 필요한 널 문자를 컴파일러가 더함.
* Str3 처럼 명식적으로 널 문자를 더함
* Str4 처럼 따옴표 안에 스트링 상수로 초기화; 컴파일러는 배열 크기를 문자열 상수에 맞게 끝 널 문자를 맞춤 
* Str5 처럼 명시적 크기와 문자열 상수로 배열 초기화
* Str6 처럼 배열을 초기화하고, 여분 공간을 남겨서 초기화

*널 끝내기*
일반적으로, 문자열은 널 문자(아스키 코드 0)로 끝난다. 이것은 함수가 문자열의 끝이 어디인지 알 수 있다. 그렇지 않으면, 실제로는 문자열의 부분이 아닌 후속 바이트를 계속 읽을 것이다.
이것은 문자열이 당신이 원하는 것을 담기 위해 문자 하나 더 공간을 가져야 함을 뜻한다. 그것이 Str2 와 Str5 가 문자를 필요로 하는 까닭이다.
 only seven - the last position is automatically filled with a null character. Str4 will be automatically sized to eight characters, one for the extra null. In Str3, we've explicitly included the null character (written '\0') ourselves.

Note that it's possible to have a string without a final null character (e.g. if you had specified the length of Str2 as seven instead of eight). This will break most functions that use strings, so you shouldn't do it intentionally. If you notice something behaving strangely (operating on characters not in the string), however, this could be the problem.

*작은 따옴표 큰 따옴표?*

Strings are always defined inside double quotes ("Abc") and characters are always defined inside single quotes('A').

*긴 문자열 줄 바꾸기*

긴 스트링을 아래와 같이 랩 할 수 있다:

[source,arduino]
----
char myString[] = "This is the first line"
" this is the second line"
" etcetera";
----

*문자열의 배열*

It is often convenient, when working with large amounts of text, such as a project with an LCD display, to setup an array of strings. Because strings themselves are arrays, this is in actually an example of a two-dimensional array.

In the code below, the asterisk after the datatype `char` "`char*`" indicates that this is an array of "`pointers`". All array names are actually pointers, so this is required to make an array of arrays. Pointers are one of the more esoteric parts of C for beginners to understand, but it isn't necessary to understand pointers in detail to use them effectively here.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 예제 코드
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
char* myStrings[]={"This is string 1", "This is string 2", "This is string 3",
"This is string 4", "This is string 5","This is string 6"};

void setup(){
Serial.begin(9600);
}

void loop(){
for (int i = 0; i < 6; i++){
   Serial.println(myStrings[i]);
   delay(500);
   }
}
----


--
// HOW TO USE SECTION ENDS

// SEE ALSO SECTION STARTS
[#see_also]
--

[float]
=== 더 볼 것

[role="language"]
* #LANGUAGE# link:../../utilities/progmem[PROGMEM]

--
// SEE ALSO SECTION ENDS
