---
title: ">"
title_expanded: greater than
categories: [ "Data Types" ]
subCategories: [ "스트링개체 연산자" ]
---





= > Greater Than


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
Tests if the string on the left is greater than the string on the right. This operator evaluates strings in alphabetical order, on the first character where the two differ. So, for example "b" > "a" and "2" > "1", but "999" > "1000" because 9 comes after 1.

Caution: String comparison operators can be confusing when you're comparing numeric strings, because the numbers are treated as strings and not as numbers. If you need to compare numbers numerically, compare them as ints, floats, or longs, and not as Strings.
[%hardbreaks]


[float]
=== 문법
[source,arduino]
----
string1 > string2
----

[float]
=== 매개변수
`string1, string2` - a string variable

[float]
=== 반환
`true`: if string1 is greater than string2 

`false`: otherwise

--

// OVERVIEW SECTION ENDS



// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 더 볼 것

[role="example"]
* #EXAMPLE# link: https://www.arduino.cc/en/Tutorial/BuiltInExamples#strings[Built-in String Tutorials]
--
// SEE ALSO SECTION ENDS