---
title: for
categories: [ "Structure" ]
subCategories: [ "제어 구조" ]
---





= for 루프


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
`for` 문은 중괄호로 둘러싸인 문의 블록을 반복할 때 사용된다
증가 카운터가 루프를 증가하고 끝내는 데 쓰인다. `for` 문은 반복 연산에 쓸모있고, 자료/핀의 모임에서 연산하는 배열을 가진 조합에 자주 쓰인다.
[%hardbreaks]


[float]
=== 문법
[source,arduino]
----
for (initialization; condition; increment) {
	//statement(s);
}
----

The *initialization* happens first and exactly once. Each time through the loop, the *condition* is tested; if it's `true`, the statement block, and the *increment* is executed, then the *condition* is tested again. When the *condition* becomes `false`, the loop ends.
[%hardbreaks]

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 예제 코드
[source,arduino]
----
// Dim an LED using a PWM pin
int PWMpin = 10; // LED in series with 470 ohm resistor on pin 10

void setup()
{
  // no setup needed
}

void loop()
{
   for (int i=0; i <= 255; i++){
      analogWrite(PWMpin, i);
      delay(10);
   }
}
----
[%hardbreaks]

[float]
=== 주의와 경고
C `for` 루프는 다른 컴퓨터 언어, BASIC 포함,에서 발견되는 `for` 루프보다 좀더 유연하다.
세미콜론은 필요하지만 3개 헤더 요소중 어느 것도 생략될 수 있다. 
Also the statements for initialization, condition, and increment can be any valid C statements with unrelated variables, and use any C datatypes including floats. These types of unusual `for` statements may provide solutions to some rare programming problems.
[%hardbreaks]

For example, using a multiplication in the increment line will generate a logarithmic progression:

[source,arduino]
----
for(int x = 2; x < 100; x = x * 1.5){
println(x);
}
----

생성하는 것: 2,3,4,6,9,13,19,28,42,63,94
[%hardbreaks]

다른 예는, LED를 하나의 `for` 루프로 점점 밝게 그리고 어둡게:

[source,arduino]
----
void loop()
{
   int x = 1;
   for (int i = 0; i > -1; i = i + x){
      analogWrite(PWMpin, i);
      if (i == 255) x = -1;             // 정점에서 방향 바꿈
      delay(10);
   }
}
----


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== 더 볼 것

[role="language"]

--
// SEE ALSO SECTION ENDS
