---
title: analogRead()
categories: [ "Functions" ]
subCategories: [ "아날로그 입출력" ]
---

= analogRead()

// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
특정 핀에서 값을 읽는다. 아두이노 보드는 6채널(미니와 나노는 8채널, 메가는 16채널), 10비트 아나로그에서 디지털로 변환기를 포함한다. 이것은 0에서 5V 사이의 입력 전압을 0에서 1024 사이의 값으로 매핑하는 것을 뜻한다.
이것은 5볼트 / 1024 단위 즉 단위당 .0049볼트(4.9mV) 분해능을 낸다.
입력 범위와 분해능은 link:../analogreference[analogReference()] 을 써서 바뀔 수 있다.


아나로그 입력을 읽는 데는 약 100마이크로초(0.0001초) 걸리므로, 최대 읽기율은 1초에 약 1만번이다.
[%hardbreaks]


[float]
=== 문법

`analogRead(pin)`

[float]
=== 매개변수
`pin`: 읽을 아나로그 입력 핀(대부분 보드에서 0에서 5까지, 미니와 나노에서 0에서 7까지, 메가에서 0에서 15까지) 번호

[float]
=== 반환
int(0 에서 1023)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 예제 코드
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
이 코드는 아나로그 핀의 전압을 읽어서 표시한다.


[source,arduino]
----
int analogPin = 3;     // 전위차계 와이퍼(중간 단자)가 아나로그 핀 3에 연결됨
                       // 바깥쪽은 그라운드와 +5
int val = 0;           // 읽은 값 저장할 변수

void setup()
{
  Serial.begin(9600);              //  시리얼 설정
}

void loop()
{
  val = analogRead(analogPin);     // 입력 핀 읽음
  Serial.println(val);             // 값 디버그
}
----
[%hardbreaks]

[float]
=== 주의와 경고
아나로그 핀이 아무데도 연결되지 않으면, analogRead()가 반환하는 값은 여러 요인(e.g. 다른 아나로그 입력 값, 여러분의 손이 보드에 얼마나 가까운가 등)에 따라 변한다


--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 더 볼 것

[role="language"]
* #LANGUAGE# link:../../zero-due-mkr-family/analogreadresolution[analogReadResolution()]
* #LANGUAGE# https://www.arduino.cc/en/Tutorial/AnalogInputPins[Tutorial: Analog Input Pins]
--
// SEE ALSO SECTION ENDS
