---
title: analogReference()
categories: [ "Functions" ]
subCategories: [ "아날로그 입출력" ]
---


//


= analogReference()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
아날로그 입력에 사용되는 참조 전압(즉, 입력 범위의 최댓값이 되는 전압)을 설정합니다. 옵션은 다음과 같습니다:

아두이노 AVR 보드 (Uno, Mega 등)

* DEFAULT: 기본 아날로그 참조 전압값인 5V (5V 아두이노 보드에서) 또는 3.3 V (3.3V 아두이노 보드에서)
* INTERNAL: 내장 참조 전압, ATmega168 또는 ATmega328P에서 1.1V, ATmega8에서는 2.56V (아두이노 메가에서는 사용 불가)
* INTERNAL1V1: 내장된 1.1V 참조 전압 (아두이노 메가 전용)
* INTERNAL2V56: 내장된 2.56V 참조 전압 (아두이노 메가 전용)
* EXTERNAL: AREF 핀(0에서 5V 전용)에 인가된 전압을 참조 전압으로써 사용
[%hardbreaks]

아두이노 SAMD 보드 (Zero 등)
* AR_DEFAULT: 3.3V짜리 기본 아날로그 참조 전압
* AR_INTERNAL: 내장 2.23V 참조 전압
* AR_INTERNAL1V0: 내장 1.0V 참조 전압
* AR_INTERNAL1V65: 내장 1.65V 참조 전압
* AR_INTERNAL2V23: 내장 2.23V 참조 전압
* AR_EXTERNAL: AREF 핀(0에서 5V 전용)에 인가된 전압을 참조 전압으로써 사용

아두이노 SAM 보드 (Due)
* AR_DEFAULT: 3.3V의 기본 아날로그 참조 전압. 이 옵션은 Due만 지원합니다.

[float]
=== 문법
`analogReference(type)`


[float]
=== 매개변수
`type`: 사용할 참조 전압의 종류 (설명 문단의 옵션 참조).

[float]
=== 반환
없음

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 주의와 경고
아날로그 참조 값을 바꾼 후, 처음 몇 번 `analogRead()` 에서 읽는 값은 정확하지 않을 수 있습니다.
*AREF 핀에 외부 참조 전압으로써 0V보다 작거나 5V보다 큰 것을 사용하지 마세요!
AREF 핀을 통해 외부 참조를 쓰려면, 아날로고 참조를 EXTERNAL로 한 다음 `analogRead()` 를 부르세요.*
그러지 않으면, 활성화된 참조 전압(내부에서 만들어진)과 AREF 핀이 합선되어, 아두이노 보드의 마이크로컨트롤러를 망가뜨릴 수 있습니다.
또는, 외부 참조 전압을 5K 저항을 거쳐 연결하여, 외부와 내부 참조 전압 사이를 전환할 수 있습니다.
AREF 핀에 32K옴짜리 내부 저항이 있기 때문에, 5K옴 저항이 참조로 사용되는 전압을 바꿀 것입니다. 두 저항은 전압 분배기로 동작하기 때문에, 예를 들어, 저항에 2.5V가 걸리면 AREF 핀에는 2.5 * 32 / (32 + 5) = 약 2.2V가 걸릴 것입니다.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 더보기

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/AnalogInputPins[Description of analog input pins]

--
// SEE ALSO SECTION ENDS
