---
title: analogReference()
categories: [ "Functions" ]
subCategories: [ "아날로그 입출력" ]
---


//


= analogReference()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
아날로그 입력에 쓰이는 참조 전압(즉 입력 범위 꼭대기에 쓰이는 값)을 구성. 옵션은 :


* DEFAULT: 5V 의 기본 아날로그 참조 값(5V 아두이노 보드에서) 또는 3.3 V (3.3V 아두이노 보드에서)
* INTERNAL: 내장된 참조, 1.1 V ATmega168 또는ATmega328P 에서, 그리고 2.56 V ATmega8 에서(아두이노 메가에서는 안 됨)
* INTERNAL1V1: 내장된 1.1V 참조 (아두이노 메가 전용)
* INTERNAL2V56: 내장된 2.56V 참조 (아두이노 메가 전용)
* EXTERNAL: AREF 핀(0에서 5V 전용)에 적용되는 전압이 참조로 쓰임
[%hardbreaks]


[float]
=== 문법
`analogReference(type)`


[float]
=== 매개변수
`type`: 사용할 참조 타입 (DEFAULT, INTERNAL, INTERNAL1V1, INTERNAL2V56, 또는 EXTERNAL).

[float]
=== 반환
없음

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 주의와 경고
아날로그 참조를 바꾼 후, `analogRead()`  로부터의 처음 몇 읽기는 정확하지 않을 수 있다.
*AREF 핀에 외부 참조 전압으로 0V보다 작거나 5V보다 큰 것을 쓰지 마세요!
AREF 핀에 외부 참조를 쓰려면, 아날로고 참조를 EXTERNAL 로 한 다음 `analogRead()` 를 부르세요.*
그러지 않으면, 활성 참조 전압(내부에서 만들어진)과 AREF 핀이 합선되어, 아두이노 보드의 마이크로컨트롤러를 망가뜨릴 수 있다.
또는, 외부 참조 전압을 5K 저항을 통해 연결하여, 외부와 내부 참조 전압 간에 전환할 수 있다.
저항이 참조로 사용되어 얻는 전압을 바꿀 것인데 왜냐면 내부 32K 저항이 AREF 핀에 있기 때문이다.
그 둘은 전압 분배기로 동작해서, 예를들어 저항을 통해 2.5V가 적용되면 AREF 핀에 2.5 * 32 / (32 + 5) = ~2.2V 가 된다.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 더 볼 것

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/AnalogInputPins[Description of analog input pins]

--
// SEE ALSO SECTION ENDS
