---
title: analogReference()
categories: [ "Functions" ]
subCategories: [ "아날로그 입출력" ]
---


//


= analogReference()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
아날로그 입력에 쓰이는 참조 전압(즉 입력 범위 꼭대기에 쓰이는 값)을 구성. 옵션은 :


* DEFAULT: 5V 의 기본 아날로그 참조 값(5V 아두이노 보드에서) 또는 3.3 V (3.3V 아두이노 보드에서)
* INTERNAL: 내장된 참조, 1.1 V ATmega168 또는ATmega328P 에서, 그리고 2.56 V ATmega8 에서(아두이노 메가에서는 안 됨)
* INTERNAL1V1: 내장된 1.1V 참조 (아두이노 메가 전용)
* INTERNAL2V56: 내장된 2.56V 참조 (아두이노 메가 전용)
* EXTERNAL: the voltage applied to the AREF pin (0 to 5V only) is used as the reference.
[%hardbreaks]


[float]
=== 문법
`analogReference(type)`


[float]
=== 매개변수
`type`: 사용할 참조 타입 (DEFAULT, INTERNAL, INTERNAL1V1, INTERNAL2V56, 또는 EXTERNAL).

[float]
=== 반환
없음

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 주의와 경고
After changing the analog reference, the first few readings from `analogRead()` may not be accurate.

*Don't use anything less than 0V or more than 5V for external reference voltage on the AREF pin! If you're using an external reference on the AREF pin, you must set the analog reference to EXTERNAL before calling `analogRead()`.* Otherwise, you will short together the active reference voltage (internally generated) and the AREF pin, possibly damaging the microcontroller on your Arduino board.

Alternatively, you can connect the external reference voltage to the AREF pin through a 5K resistor, allowing you to switch between external and internal reference voltages. Note that the resistor will alter the voltage that gets used as the reference because there is an internal 32K resistor on the AREF pin. The two act as a voltage divider, so, for example, 2.5V applied through the resistor will yield 2.5 * 32 / (32 + 5) = ~2.2V at the AREF pin.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 더 볼 것

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/AnalogInputPins[Description of analog input pins]

--
// SEE ALSO SECTION ENDS
