---
title: interrupts()
categories: [ "Functions" ]
subCategories: [ "인터럽트" ]
---





= interrupts()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
interrupts 를 다시 가능하게 (link:../nointerrupts[nointerrupts()] 에 의해 불가능하게 된 후).
Interrupts allow certain important tasks to happen in the background and are enabled by default. Some functions will not work while interrupts are disabled, and incoming communication may be ignored. Interrupts can slightly disrupt the timing of code, however, and may be disabled for particularly critical sections of code.
[%hardbreaks]


[float]
=== 문법
`interrupts()`


[float]
=== 매개변수
Nothing

[float]
=== 반환
Nothing

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 예제 코드
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code enables Interrupts.

[source,arduino]
----
void setup() {}

void loop()
{
  noInterrupts();
  // critical, time-sensitive code here
  interrupts();
  // other code here
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 더 볼 것

[role="language"]
* #LANGUAGE# link:../../external-interrupts/attachinterrupt[attachInterrupts()]
* #LANGUAGE# link:../../external-interrupts/detachinterrupt[detachInterrupts()]

--
// SEE ALSO SECTION ENDS
