---
title: randomSeed()
categories: [ "Functions" ]
subCategories: [ "난수" ]
---





= randomSeed(seed)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
`randomSeed()` 는 의사난수 생성기를 초기화하며, 임의 열에서 임의 위치에서 시작하게 한다.
이 열은, 아주 길지만, 임의지만 늘 똑같다.

If it is important for a sequence of values generated by `random()` to differ, on subsequent executions of a sketch, use randomSeed() to initialize the random number generator with a fairly random input, such as `analogRead()` on an unconnected pin.

Conversely, it can occasionally be useful to use pseudo-random sequences that repeat exactly. This can be accomplished by calling `randomSeed()` with a fixed number, before starting the random sequence.
[%hardbreaks]





[float]
=== 매개변수
`long`, `int` - 시드를 만들기 위해 숫자를 전달.

[float]
=== 반환
없음

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
===
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
The code generates a pseudo-random number and sends the generated number to the serial port.

[source,arduino]
----
long randNumber;              //랜덤 값을 저장할 long 타입 변수 선언

void setup() {
  Serial.begin(9600);         //랜덤 값을 씨리얼모니터로 확인하기위해 씨리얼통신을 시작하는 함수
  randomSeed(analogRead(0));  //randomSeed의 매개변수로 0번 채널(A0번 핀)에서 읽은 아날로그 값을 전달
}

void loop() {
  randNumber = random(300);   //randNumber 변수에 0 ~ 299 값 중 랜덤한 값을 저장
  Serial.println(randNumber); //randNumber 변수의 값을 씨리얼모니터에 한 줄로 출력

  delay(50);                  //0.05초 지연 후 다음 루프 실행
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

--
// SEE ALSO SECTION ENDS
