---
title: randomSeed()
categories: [ "Functions" ]
subCategories: [ "난수" ]
---





= randomSeed(seed)


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
`randomSeed()` 는 의사난수 생성기를 초기화하며, 임의 열에서 임의 위치에서 시작하게 한다.
이 열은, 아주 길지만, 임의지만 늘 똑같다.

If it is important for a sequence of values generated by `random()` to differ, on subsequent executions of a sketch, use randomSeed() to initialize the random number generator with a fairly random input, such as `analogRead()` on an unconnected pin.

Conversely, it can occasionally be useful to use pseudo-random sequences that repeat exactly. This can be accomplished by calling `randomSeed()` with a fixed number, before starting the random sequence.
[%hardbreaks]





[float]
=== 매개변수
`long`, `int` - 시드를 만들기 위해 숫자를 전달.

[float]
=== 반환
없음

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 예제 코드
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
코드 설명 필요.

[source,arduino]
----
long randNumber;

void setup(){
  Serial.begin(9600);
  randomSeed(analogRead(0));
}

void loop(){
  randNumber = random(300);
  Serial.println(randNumber);

  delay(50);
}
----

--
// HOW TO USE SECTION ENDS
