---
title: Keyboard.write()
---




= Keyboard.write()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
키 입력을 연결된 컴퓨터에 보낸다.
이것은 키보드에서 키를 누르고 떼는 것과 비슷하다.
ASCII 문자 또는 추가 link:../keyboardmodifiers[keyboard modifiers and special keys] 를  보낼 수 있다.

키보드에 있는 ASCII 문자만 지원된다.
예를들어,ASCII 8 (백스페이스) 은 동작하지만 ASCII 25 (Substitution) 은 안 된다.
대문자를 보낼 때, Keyboard.write() 는 키보드에서 치는 것처럼 shift 명령 더하기 원하는 문자를 보낸다.
숫자 형을 보내면, ASCII 문자로 보낸다(예. Keyboard.write(97) 는 'a'를 보냄).

ASCII 문자 전체 목록은, http://www.asciitable.com/[ASCIITable.com] 을 보세요.
[%hardbreaks]


[float]
=== 문법
`Keyboard.write(character)`


[float]
=== 매개변수
`character` : 컴퓨터에 보낼 char 또는 int.
char 에 허용되는 어느 표기법이든 보낼 수 있다.
예를들어, 아래 모두 가능하며 65 나 ASCII A나 같은 값을 보낸다:
[source,arduino]
----
Keyboard.write(65);         // sends ASCII value 65, or A
Keyboard.write('A');            // same thing as a quoted character
Keyboard.write(0x41);       // same thing in hexadecimal
Keyboard.write(0b01000001); // same thing in binary (weird choice, but it works)
----

[float]
=== 반환
`size_t` : number of bytes sent.

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 예제 코드
// Describe what the example code is all about and add relevant code


[source,arduino]
----
#include <Keyboard.h>

void setup() {
  // make pin 2 an input and turn on the
  // pullup resistor so it goes high unless
  // connected to ground:
  pinMode(2, INPUT_PULLUP);
  Keyboard.begin();
}

void loop() {
  //if the button is pressed
  if(digitalRead(2)==LOW){
    //Send an ASCII 'A',
    Keyboard.write(65);
  }
}
----
[%hardbreaks]

[float]
=== 주의와 경고
Keyboard.write() 명령을 쓰면, 아두이노가 여러분의 키보드를 받습니다!
명령을 쓰기 전에 제어권을 갖고 있는지 확인하세요.
키보드 제어 상태를 토글하는 푸시버튼이 효과적이다.

--
// HOW TO USE SECTION ENDS
