---
title: constants
categories: [ "Variables" ]
subCategories: [ "상수" ]
---





= 상수


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
== 설명
상수는 Arduino 언어에서 미리 정의된 표현식이다. 그것들은 프로그램을 읽기 쉽게 하기 위해 사용된다. 그룹으로 상수를 분류한다:

[float]
== 논리 수준 정하기: true 그리고 false (Boolean 상수)
아두이노 언어에서 참과 거짓을 표현하기 위해 사용되는 두 상수가 있다: `true`, 그리고 `false`.

[float]
=== false
`false` 둘 중에 정의하기 쉽다. false 는 0 (zero)으로 정의된다.
[%hardbreaks]

[float]
=== true
`true` 는 1로 정의된다고 흔히 말하지만, 맞지만, true는 더 넓은 정의가 있다.
영 아닌 정수는 부울 의미로 true이다. 그래서 부울 의미로 -1, 2 그리고 -200 모두 true로 정의된다.

[%hardbreaks]
`true` 및 `false` 상수는  `HIGH`, `LOW`, `INPUT`, 그리고 `OUTPUT` 와 달리 소문자로 침을 유의하라.
[%hardbreaks]

[float]
== 핀 수준 정의: HIGH 및 LOW
디지털 핀에 읽거나 쓸 때 핀이 얻고/설정 할 수 있는 것은 오직 두 값만 있다: `HIGH` 및 `LOW`.

[float]
=== HIGH
The meaning of `HIGH` (in reference to a pin) is somewhat different depending on whether a pin is set to an `INPUT` or `OUTPUT`. When a pin is configured as an `INPUT` with link:../../../functions/digital-io/pinmode[pinMode()], and read with link:../../../functions/digital-io/digitalread[digitalRead()], the Arduino (ATmega) will report `HIGH` if:

  - a voltage greater than 3.0V is present at the pin (5V boards)
  - a voltage greater than 2.0V volts is present at the pin (3.3V boards)
[%hardbreaks]

A pin may also be configured as an INPUT with `pinMode()`, and subsequently made HIGH with link:../../../functions/digital-io/digitalwrite[digitalWrite()]. This will enable the internal 20K pullup resistors, which will _pull up_ the input pin to a `HIGH` reading unless it is pulled `LOW` by external circuitry. This is how `INPUT_PULLUP` works and is described below in more detail.
[%hardbreaks]

When a pin is configured to OUTPUT with `pinMode()`, and set to `HIGH` with `digitalWrite()`, the pin is at:

  - 5 volts (5V boards)
  - 3.3 volts (3.3V boards)

In this state it can source current, e.g. light an LED that is connected through a series resistor to ground.
[%hardbreaks]

[float]
=== LOW
The meaning of `LOW` also has a different meaning depending on whether a pin is set to `INPUT` or `OUTPUT`. When a pin is configured as an `INPUT` with `pinMode()`, and read with `digitalRead()`, the Arduino (ATmega) will report LOW if:

  - a voltage less than 1.5V is present at the pin (5V boards)
  - a voltage less than 1.0V (Approx) is present at the pin (3.3V boards)

When a pin is configured to `OUTPUT` with `pinMode()`, and set to `LOW` with `digitalWrite()`, the pin is at 0 volts (both 5V and 3.3V boards). In this state it can sink current, e.g. light an LED that is connected through a series resistor to +5 volts (or +3.3 volts).
[%hardbreaks]

[float]
== Defining Digital Pins modes: INPUT, INPUT_PULLUP, and OUTPUT
Digital pins can be used as `INPUT`, `INPUT_PULLUP`, or `OUTPUT`. Changing a pin with `pinMode()` changes the electrical behavior of the pin.

[float]
=== INPUT 으로 구성ᅟ된 핀
Arduino (ATmega) pins configured as `INPUT` with `pinMode()` are said to be in a _high-impedance_ state. Pins configured as `INPUT` make extremely small demands on the circuit that they are sampling, equivalent to a series resistor of 100 Megohms in front of the pin. This makes them useful for reading a sensor.
[%hardbreaks]

If you have your pin configured as an `INPUT`, and are reading a switch, when the switch is in the open state the input pin will be "floating", resulting in unpredictable results. In order to assure a proper reading when the switch is open, a pull-up or pull-down resistor must be used. The purpose of this resistor is to pull the pin to a known state when the switch is open. A 10 K ohm resistor is usually chosen, as it is a low enough value to reliably prevent a floating input, and at the same time a high enough value to not not draw too much current when the switch is closed. See the http://arduino.cc/en/Tutorial/DigitalReadSerial[Digital Read Serial^] tutorial for more information.
[%hardbreaks]

If a pull-down resistor is used, the input pin will be `LOW` when the switch is open and `HIGH` when the switch is closed.
[%hardbreaks]

If a pull-up resistor is used, the input pin will be `HIGH` when the switch is open and `LOW` when the switch is closed.
[%hardbreaks]

[float]
=== INPUT_PULLUP으로 구성된 핀
The ATmega microcontroller on the Arduino has internal pull-up resistors (resistors that connect to power internally) that you can access. If you prefer to use these instead of external pull-up resistors, you can use the `INPUT_PULLUP` argument in `pinMode()`.
[%hardbreaks]

See the http://arduino.cc/en/Tutorial/InputPullupSerial[Input Pullup Serial^] tutorial for an example of this in use.
[%hardbreaks]

Pins configured as inputs with either `INPUT` or `INPUT_PULLUP` can be damaged or destroyed if they are connected to voltages below ground (negative voltages) or above the positive power rail (5V or 3V).
[%hardbreaks]

[float]
=== OUTPUT으로 구성된 핀
Pins configured as `OUTPUT` with `pinMode()` are said to be in a _low-impedance_ state. This means that they can provide a substantial amount of current to other circuits. ATmega pins can source (provide current) or sink (absorb current) up to 40 mA (milliamps) of current to other devices/circuits. This makes them useful for powering LEDs because LEDs typically use less than 40 mA. Loads greater than 40 mA (e.g. motors) will require a transistor or other interface circuitry.
[%hardbreaks]

Pins configured as outputs can be damaged or destroyed if they are connected to either the ground or positive power rails.
[%hardbreaks]

[float]
== 빌트 인 정의 : LED_BUILTIN
Most Arduino boards have a pin connected to an on-board LED in series with a resistor. The constant `LED_BUILTIN` is the number of the pin to which the on-board LED is connected. Most boards have this LED connected to digital pin 13.

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--

--
// HOW TO USE SECTION ENDS

// SEE ALSO  SECTION BEGINS
[#see_also]
--

[float]
=== 더 볼 것

[role="language"]

--
// SEE ALSO SECTION ENDS
