---
title: 정수 상수
categories: [ "Variables" ]
subCategories: [ "Constants" ]
---





= 정수 상수


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
정수 상수는 123처럼 스케치에서 직접 사용되는 숫자이다. 기본으로, 이 숫자들은 link:../../data-types/int[int] 로 취급되지만 U와 L 변경자로 이것을 바꿀 수 있다(아래를 보세요)
[%hardbreaks]

보통, 정수 상수는 십진수(decimal)로 취급되지만, 특별한 표기(포매터)가 쓰여져서 다른 진법으로 쓰일 수 있다.
[%hardbreaks]

|===
|밑 |예 |포매터 |설명

|10 (decimal)
|123
|none
|

|2 (binary)
|B1111011
|선행 'B'
|오직 8비트 값 (0 to 255) 문자 0&1 만 타당

|8 (octal)
|0173
|선행 "0"
|문자 0-7 타당

|16 (hexadecimal)
|0x7B
|l선행 "0x"
|문자 0-9, A-F, a-f 타당
|===
[%hardbreaks]

--
// OVERVIEW SECTION ENDS



// HOW TO USE SECTION STARTS
[#howtouse]
--
[float]
== Decimal (밑 10)

이것은 여러분이 알고 있는 보통 수학이다. 다른 접두어 없는 상수는 십진수 형으로 가정한다.

[float]
=== 예제 코드:
[source,arduino]
----
n = 101;     // 101 십진수   ((1 * 10^2) + (0 * 10^1) + 1)
----

[%hardbreaks]

[float]
== Binary (밑 2)
문자 0 과 1 만 타당.

[float]
=== 예제 코드:
[source,arduino]
----
n = B101;    // decimal 5와 같음  ((1 * 2^2) + (0 * 2^1) + 1)
----

바이너리 포매터는 0(B0)과 255(B11111111) 사이의 바이트(8비트)에서만 동작한다.
입력을 바이너리 포맷으로 하는 게 편하면 아래와 같은 2단계를 할 수 있다:

입력을 
If it is convenient to input an int (16 bits) in binary form you can do it a two-step procedure such as:
[source,arduino]
----
myInt = (B11001100 * 256) + B10101010;    // B11001100 is the high byte`
----
[%hardbreaks]

[float]
== Octal (base 8)
0에서 , 7까지의 문자만 타당. 8진수 값은 선
Only the characters 0 through 7 are valid. Octal values are indicated by the prefix "0" (zero).

[float]
=== Example  Code:
[source,arduino]
----
n = 0101;    // same as 65 decimal   ((1 * 8^2) + (0 * 8^1) + 1)
----
It is possible to generate a hard-to-find bug by (unintentionally) including a leading zero before a constant and having the compiler unintentionally interpret your constant as octal.
[%hardbreaks]

[float]
== Hexadecimal (base 16)
Valid characters are 0 through 9 and letters A through F; A has the value 10, B is 11, up to F, which is 15. Hex values are indicated by the prefix "0x". Note that A-F may be syted in upper or lower case (a-f).

[float]
=== Example  Code:
[source,arduino]
----
n = 0x101;   // same as 257 decimal   ((1 * 16^2) + (0 * 16^1) + 1)
----
[%hardbreaks]


[float]
=== Notes and Warnings
*U & L formatters:*

By default, an integer constant is treated as an int with the attendant limitations in values. To specify an integer constant with another data type, follow it with:

  - a 'u' or 'U' to force the constant into an unsigned data format. Example: 33u
  - a 'l' or 'L' to force the constant into a long data format. Example: 100000L
  - a 'ul' or 'UL' to force the constant into an unsigned long constant. Example: 32767ul

[%hardbreaks]

--
// HOW TO USE SECTION ENDS




// SEE ALSO SECTION BEGINS
[#see_also]
--

[float]
=== See also

[role="language"]

--
// SEE ALSO SECTION ENDS
