---
title: Serial.readBytesUntil()
---




= Serial.readBytesUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
Serial.readBytesUntil() reads characters from the serial buffer into an array. The function terminates if the terminator character is detected, the determined length has been read, or it times out (see link:../settimeout[Serial.setTimeout()]).

`Serial.readBytesUntil()` returns the number of characters read into the buffer. A 0 means no valid data was found.

`Serial.readBytesUntil()` inherits from the link:../../stream[Stream] utility class.
[%hardbreaks]


[float]
=== 문법
`Serial.readBytesUntil(character, buffer, length)`


[float]
=== 매개변수
`character` : the character to search for (`char`)

`buffer`: the buffer to store the bytes in (`char[]` or `byte[]`)

`length` : the number of bytes to read (`int`)

[float]
=== 반환
`size_t`

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 더 볼 것

[role="language"]
* #LANGUAGE# link:../../stream[Stream]
* #LANGUAGE# link:../../stream/streamreadbytesuntil[Stream.readByteUntil()]

--
// SEE ALSO SECTION ENDS
