---
title: pulseInLong()
categories: [ "Functions" ]
subCategories: [ "고급 입출력" ]
---





= pulseInLong()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
핀에서 펄스(HIGH 또는 LOW)를 읽는다.
예를들어, *값* 이 *HIGH* 이면, `pulseInLong()` 는 핀이 *HIGH* 로 갈 때를 기다리고, 타이밍을 시작하고, 그러면 핀이 *LOW* 가 될 때를 기다리고 타이밍을 멈춘다.
펄스의 길이를 마이크로 초로 반환한다. 특정 타임 아웃 안에 펄스 시작 없으면 0을 반환.
이 함수의 타이밍은 경험적으로 결정되어 긴 펄스에서 에러를 보일 수도 있다.
10 마이크로 초에서 3분 길이까지 동작한다.
함수가 불렸을 때 핀이 이미 HIGH 이면, 핀이 LOW 갈 때를 기다리고 그러면 카운팅을 시작하기 전에 HIGH이다. 이 루틴은 인터럽트가 활성되었을 때만 쓸 수 있다. 게다가 가장 높은 해상도는 큰 간격으로 얻을 수 있다.
[%hardbreaks]


[float]
=== 문법
`pulseInLong(pin, value)`

`pulseInLong(pin, value, timeout)`

[float]
=== 매개변수
`pin`: 펄스를 읽을 핀 번호. (int)

`value`: 읽을 펄스 형: either link:../../../variables/constants/constants/[HIGH] 또는 link:../../../variables/constants/constants/[LOW]. (int)

`timeout` (옵션): 펄스 시작을 기다릴 마이크로 초 수; 기본값은 1초 (unsigned long)

[float]
=== 반환
펄스 길이 (마이크로 초) 또는 0(타임아웃 시작되기전에 펄스 없으면) (unsigned long)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 예제 코드
// Describe what the example code is all about and add relevant code
이 예는 핀 7에서 펄스의 지속시간을 계산.

[source,arduino]
----
int pin = 7;
unsigned long duration;

void setup() {
  pinMode(pin, INPUT);
}

void loop() {
  duration = pulseInLong(pin, HIGH);
}
----
[%hardbreaks]

[float]
=== 주의와 경고
이 함수는 micros() 에 의존하므로 link:../../interrupts/nointerrupts[noInterrupts()] 컨텍스트에 쓸 수 없다.

--
// HOW TO USE SECTION ENDS
