---
title: tone()
categories: [ "Functions" ]
subCategories: [ "Advanced I/O" ]
---





= tone()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
한 핀에 특정 주파수(그리고 50% 듀티 사이클)의 구형파를 생성한다. 지속시간을 명시할 수 있으며, 그러지 않으면 그 파가 link:../noTone[noTone()] 을 부를 때까지 계속됩니다. 핀을 피에조 부저 또는 다른 스피커에 연결하여 tone 을 연주할 수 있다.

한번에 한 tone 만 생성될 수 있다. tone 이 다른 핀에서 이미 연주되고 있으면, tone() 을 부르면 효과 없다. 같은 핀에서 tone 을 연주하면, 주파수를 설정한다.

`tone()` 함수의 사용은 PWM 출력 핀 3 과 11(Mega 와 다른 보드)에서 PWM 출력을 방해할 거다.
31HZ보다 낮은 tone 을 만드는 건 불다능하다. 기술적 상세는, https://github.com/bhagman/Tone#ugly-details[Brett Hagman's notes] 를 보시오.
[%hardbreaks]


[float]
=== 문법
`tone(pin, frequency)`

`tone(pin, frequency, duration)`
[%hardbreaks]

[float]
=== Parameters
`pin`: tone 생성할 핀

`frequency`: tone 의 주파수 (hertz )- `unsigned int`

`duration`: tone 의 지속시간 (단위 milliseconds (선택사항)) - `unsigned long`
[%hardbreaks]

[float]
=== 반환
없음

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 주의와 경고
여러 핀에 다른 피치를 연주하려면 다음 핀에 ` tone() ` 을 부르기 전에 noTone()` 을  불려야 함
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 더 볼 것

[role="language"]
* #LANGUAGE# link:../../analog-io/analogwrite[analogWrite()]

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Tone^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Pitch follower^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone3[Simple Keyboard^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone4[multiple tones^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/PWM[PWM^]

--
// SEE ALSO SECTION ENDS
