---
title: tone()
categories: [ "Functions" ]
subCategories: [ "고급 입출력" ]
---





= tone()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 설명
핀에 특정 주파수(50% 듀티 사이클)의 구형파를 발생시킵니다. 지속 시간을 정할 수 있으며, 따로 정하지 않는다면 link:../noTone[noTone()]을 부를 때까지 구형파가 지속됩니다. 핀을 피에조 버저 또는 스피커에 연결하여 tone을 연주할 수 있습니다.

한번에 한 tone만 발생시킬 수 있습니다. 다른 핀에서 tone이 이미 연주되고 있으면, tone()을 새로 불러도 아무 일도 일어나지 않을 것입니다. 같은 핀에서 tone이 연주되고 있으면, 주파수가 새로 설정될 것입니다.

`tone()` 함수의 사용은 (Mega 이외의 보드에서) 3번과 11번 핀에서의 PWM 출력을 방해할 것입니다.
31HZ보다 낮은 tone을 발생시키는 것은 불가능합니다. 기술적인 세부 사항은, https://github.com/bhagman/Tone#ugly-details[Brett Hagman's notes]를 보십시오.
[%hardbreaks]


[float]
=== 문법
`tone(pin, frequency)`

`tone(pin, frequency, duration)`
[%hardbreaks]

[float]
=== 매개변수
`pin`: tone을 발생시킬 핀

`frequency`: tone의 주파수 (Hz 단위) - `unsigned int`

`duration` (옵션) : tone 의 지속 시간 (밀리초 단위) - `unsigned long`
[%hardbreaks]

[float]
=== 반환
없음

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 주의와 경고
여러 핀에서 다른 높이의 음을 내려면, 다음 핀에 대해 `tone()` 을 호출하기 전에  `noTone()` 을 호출해야 합니다.
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 더보기

[role="language"]
* #LANGUAGE# link:../../analog-io/analogwrite[analogWrite()]

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Tone Melody^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/tonePitchFollower[Pitch Follower^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone3[Tone Keyboard^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone4[Tone Multiple^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/PWM[PWM^]

--
// SEE ALSO SECTION ENDS
